///*
// * This source file was generated by the Gradle 'init' task
// */
//package Ticket_booking;
//import Ticket_booking.Entities.User;
//import Ticket_booking.Services.UserBookingService;
//import Ticket_booking.util.UserServiceUtil;
//import java.io.IOException;
//import java.util.ArrayList;
//import java.util.Scanner;
//import java.util.UUID;
//
//public class App {
//
//
//    public static void main(String[] args) {
//
//        System.out.println("RUnning Train Booking System");
//        Scanner scanner=new Scanner(System.in);
//        int option =0;
//        //load users
//        UserBookingService userBookingService = new UserBookingService(); //object declaration
////        try {
////            userBookingService = new UserBookingService();
////        } catch (Exception e) {
////            e.printStackTrace(); // VERY IMPORTANT
////        }
//
//
//        while(option != 7) {
//            System.out.println("Choose option");
//            System.out.println("1. Sign up");
//            System.out.println("2. Login");
//            System.out.println("3. Fetch Bookings");
//            System.out.println("4. Search Trains");
//            System.out.println("5. Book a Seat");
//            System.out.println("6. Cancel my Booking");
//            System.out.println("7. Exit the App");
//            option = scanner.nextInt();
//            switch(option) {
//                case 1:
//                    System.out.println("Enter the username to signup");
//                    String nameToSignUp = scanner.next();
//                    System.out.println("Enter the password to signup");
//                    String passwordToSignUp = scanner.next();
//                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
//                    userBookingService.signup(userToSignup);
//                    break;
//
//                case 2:
//                    System.out.println("Enter the username to Login");
//                    String nameToLogin = scanner.next();
//                    System.out.println("Enter the password to signup");
//                    String passwordToLogin = scanner.next();
//                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
//                    try{
//                        userBookingService = new UserBookingService(userToLogin);  //now we send user in constructor
//                    }catch (IOException ex){
//                        return;
//                    }
//                    break;
//                case 3:
//                    System.out.println("fetching your bookings");
//                    userBookingService.fetchBookings();
//                    break;
//                case 4:
//                    // Search trains
//                    break;
//                case 5:
//                    // Book seat
//                    break;
//                case 6:
//                    // Cancel booking
//                    break;
//                case 7:
//                    System.out.println("Exiting...");
//                    break;
//                default:
//                    System.out.println("Invalid option");
//            }
//        }
//
//    }
//}


package Ticket_booking;

import Ticket_booking.Entities.User;
import Ticket_booking.Services.UserBookingService;
import Ticket_booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {

        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;

        // ✅ Initialize service safely
        UserBookingService userBookingService = new UserBookingService();
        System.out.println(System.getProperty("user.dir"));
        while (option != 7) {
            System.out.println("\nChoose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");

            option = scanner.nextInt();

            switch (option) {

                case 1:
                    System.out.println("Enter username:");
                    String nameToSignUp = scanner.next();

                    System.out.println("Enter password:");
                    String passwordToSignUp = scanner.next();

                    User userToSignup = new User(
                            nameToSignUp,
                            passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>(),
                            UUID.randomUUID().toString()
                    );

                    if (userBookingService.signup(userToSignup)) {
                        System.out.println("Signup successful!");
                    } else {
                        System.out.println("Signup failed!");
                    }
                    break;

                case 2:
                    System.out.println("Enter username:");
                    String nameToLogin = scanner.next();

                    System.out.println("Enter password:");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(
                            nameToLogin,
                            passwordToLogin,
                            null,
                            new ArrayList<>(),
                            null
                    );

                    try {
                        userBookingService = new UserBookingService(userToLogin);

                        if (userBookingService.loginUser()) {
                            System.out.println("Login successful!");
                        } else {
                            System.out.println("Invalid credentials!");
                        }

                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings...");
                    userBookingService.fetchBookings();
                    break;

                case 7:
                    System.out.println("Exiting...");
                    break;

                default:
                    System.out.println("Invalid option");
            }
        }
    }
}